
# Related Work {#ch:02}

`r tufte::newthought("In recent years")`, we have witnessed an increased attention towards "green operation" of networks, which is required to support a sustainable growth of the communication infrastructures. For the case of wireless communications, there is the added motivation of a limited energy supply (i.e., batteries) in user mobile devices, which has triggered a relatively large amount of work on energy efficiency`r margincite("survey")`.

## Energy Profiling for Wireless Communications

Energy profiling is the most fundamental work on green communications. In a similar way as *software profiling* measures the duration of function calls, *energy profiling* measures the energy consumed by each software or hardware *function*, in the broad sense of the word.

There are two energy measurement techniques`r margincite("tarkoma2014smartphone")`: software- and hardware-assisted measurements. The former uses the built-in battery interface integrated in many modern devices (e.g., smartphones, tablets), which provides readings of the dicharge curve. Apart from the evident feedback loop problem^[Namely, that the software used to collect such readings is in fact producing an energy overhead.], this method lacks granularity and precision, and therefore it is not suited for fine-grained energy profiling. Despite this, it has been used in a number of papers, such as @Nurminen2008, @xiao2008, @Balasubramanian2009 and @kalic2012, some of them based on @creus2007optimizing. @dong2011self, @jung2012devscope and @xu2013v try to overcome this limitations by developing an online power model on top of the battery monitoring unit.

Instead, in hardware-assisted measurements, the battery is bypassed to directly measure the current and voltage^[User mobile devices use DC power. Therefore, the voltage signal is usually ignored and assumed to be constant, which may not be the best approach for fine-grained measurements.] signals. The current signal is converted to voltage with a small high-precision resistor, and then sampled with a variety of instruments (digital multimeters, oscilloscopes, data acquisition devices...). Thus, the granularity and precision is limited by the specific setup and instrumentation selected.

\pagebreak Typically, energy profiling studies in wireless communications provide a measurement setup that is expressly designed for the electrical specifications of the device under test. For instance, @Feeney2001 and @Jean-pierreEbert use a cardbus extender and an oscilloscope to measure wireless interfaces. @Carroll2010, @Rice2010, @Wang2010 perform energy measurements on smartphones using a data acquisition (DAQ) card, while @gupta2007 used a power meter.

More recent studies (e.g., @zhang2010accurate, @pathak2011fine, @manweiler2011avoiding, @jung2012devscope, @oliner2012collaborative, @xu2013v, @kim2013runtime, @zhang2013towards) started using the Monsoon^[[https://www.msoon.com/](https://www.msoon.com/)] Power Monitor, a product specifically designed to test smartphones which has become very popular. There have also been initiatives to design open-source energy measurement and control systems such as Energino^[[http://www.energino-project.org/](http://www.energino-project.org/)] [@riggio2012energino; @gomez2012energino].

## Energy Consumption of Network Stacks

The *classical* energy model for wireless interfaces was first established by @Feeney2001, and further confirmed by @Jean-pierreEbert and @Shih2002. Since then, it has been assumed that the network card dominates the consumption of wireless communications of mobile user devices.

This model has been widely used (implicitly or explicitly) in tens of papers to justify energy savings with optimisations of diverse kind: PHY layer rate and power [@DajiQiao], MAC parameters [@Bruno2002; @Carvalho2004; @Agrawal2004; @Jyh-ChengChen2008; @Garcia-Saavedra2011], backoff operation [@Vaidya2002; @Baiamonte2006], idle state [@Zhang2012], packet overhearing [@Ergen2007], packet relying [@He2010], data compression [@Baek2004; @Sharma2009], etcetera.

However, the work by @Serrano2014, which provides the *new* energy model studied in the previous chapter, poses doubts on prior work that propose energy efficiency strategies taking into account the wireless card only. Bearing in mind these results, it is imperative to reconsider existing schemes for energy efficiency in wireless communications. Old schemes like packet relying [@He2010] and data compression [@Baek2004; @Sharma2009] may no longer be valid under the new model. On the contrary, packet batching or low-level packet generation could potentially produce real savings.

## Micro-Sleep Opportunities in 802.11

It is well-known that the majority of nodes within any WLAN would spend most of the time in idle state. There are two main strategies to save energy in this idle time: the first one targets *idle listening* (the wireless channel is empty), and the second one targets *packet overhearing* (there are other nodes communicating). To support these savings, COTS devices have two main operational states as a function of the reference clock used: the active state and the sleep state. The more a card stays in sleep state, the less power it consumes.

Since its conception, 802.11 has attempted to minimise idle listening with the introduction of the PS mode, and some previous work followed this path. For instance, @Liu2008 proposed $\mu$PM to exploit short idle intervals ($<$100 ms) without buffering or cooperation. $\mu$PM predicts the arrival time of the next frame and puts the interface in PS mode while no arrivals are expected. This mechanism demonstrated poor granularity (tens of ms) on existing hardware and leads to performance degradation due to frame loss. Therefore, it is only suitable for low-traffic scenarios.

Others propose a PS-like operation. @Jang2011 described Snooze, an access point (AP)-directed micro-sleep scheduling and antenna configuration management method for 11n WLANs. As a consequence of its centralised design, the granularity of the so-called micro-sleeps in this approach is poor (few milliseconds), which poses doubts on its performance under heavy loads.

@Zhang2012 addressed the issue from a different standpoint with their Energy-Minimizing Idle Listening (E-MiLi). E-MiLi adaptively downclocks the card during idle periods, and reverts to full rate when an incoming frame is detected. To achieve this purpose, they need to change the physical layer (PHY) all the way down to enable downclocked detection, which severely limits the potential gains. For instance, the E-MiLi downclocking factor of 16 would yield a high power consumption in a modern card compared to its sleep state^[See Section \@ref(characterisation-of-a-cots-device).].

On the other hand, all indicators show that we should expect an exponential grow in the number of wireless devices connected. Thus, there is a rough consensus about that *densification* will become one of the main aspects of next-generation wireless networks, which brings us back to the problem of packet overhearing. In this way, the recent 11ac amendment adds the ability to save energy during TXOPs, but this mechanism is restricted to QoS traffic, and the potential sleeps are coarse, in the range of milliseconds. Any sub-millisecond approach must take into account the timing parameters of the hardware. In fact, some early studies realise the importance of this issue when WiFi technology began to take off commercially [@kamerman1997; @havinga2000; @jung2002].

@Baiamonte2006 were the first to chase fine-grained micro-sleep opportunities during packet overhearing. They define the Energy-efficient Distributed Access (EDA) scheme, which uses the 802.11 virtual carrier-sensing mechanism for power-saving purposes. Basically, a STA dozes when the Network Allocation Vector (NAV) or the backoff counter are non-zero. Unfortunately, this work lacks an empirical characterisation of the timing constraints needed to design a practical mechanism. Moreover, dozing during the backoff window is not 802.11-fair: in 802.11, STAs must sense the channel every single time slot during the contention period and, if another STA seizes the channel first, the backoff timer must be stopped in order to receive the incoming frame and set the NAV to the proper value. The EDA scheme allows STAs to doze during the contention period and, therefore, breaks the CSMA operation.

@Balaji2010 revisited the problem of packet overhearing with a scheme called Sleep during Neighbor-Addressed Frame (SNAF). With SNAF, a wireless card checks the destination MAC address and switches to sleep state during the payload duration if it was addressed to other host. They assume, without any experimental validation though, an instantaneous switch-off and that the time required to wake up is equivalent to a Short Interframe Space (SIFS). In order to prevent the risk resulting from errors in the frame header that would lead to an incorrect NAV counter, the authors propose to introduce a new framing format with a new FCS devoted to the MAC header only. This solution lacks compatibility and introduces more overhead based on no evidence.

Building on the same idea, @Prasad2014 proposed Übersleep. This time, the authors do not consider it necessary to add any extra FCS, as they claim (without any specific basis) that such errors are very unlikely.

More recently, @palacios2013a and @palacios2013b modified 802.11 DCF and PCF to exploit per-packet sleeps. They also applied these ideas to network coding [@palacios2015b] and to a polling-based version of 11ac's TXOP PS mode [@palacios2015a]. Unfortunately, all these papers rely on these early studies mentioned before [@kamerman1997; @havinga2000; @jung2002], which analysed old wireless cards unable to perform sub-millisecond transitions between states.

## Rate Adaptation and Power Control in 802.11

Rate adaptation and power control in 802.11 have received a vast amount of attention from the research community (especially the former). See, e.g., @biaz2008, @h-rca and references therein. But, as stated before, all this research is generally focused towards performance (i.e., throughput and capacity) maximisation.

However, as some previous work has pointed out [@tradeoff; @balancing], energy efficiency and performance do not necessarily come hand in hand, and some criterion may be required to set a proper balance between them. Particularly, @Li2012 and @khan2013 studied RA for energy efficiency in 802.11n, and showed that MIMO RA algorithms are not energy efficient despite ensuring high throughput. These algorithms incur inefficiencies when marginal throughput gains are achieved at a high energy cost.

No other studies have further investigated these inefficiencies in more detail though. The question remains, then, whether there may be fundamental trade-offs in the application of RA-TPC techniques to 802.11. 

## Discrete-Event Simulation of Network Systems

The list of network simulation tools is vast^[See, e.g., [http://people.idsia.ch/~andrea/sim/simnet.html](http://people.idsia.ch/~andrea/sim/simnet.html).]. Particularly, OPNET^[[http://www.opnet.com](http://www.opnet.com)] is one of the most complex and widely used tools for research and education, although the open-source alternatives, such as NS3 and OMNeT++, are growing and becoming more prominent within the research community. As an illustrative comparison, a quick search on Google Scholar^[As of April 2018.] returns over 30k results for "opnet simulation", about 6k for "omnet++ simulation" and about 12k for "ns3 simulation". Not surprisingly, the old version of the latter, NS2, still produces more than 40k results. Still, the amount of research produced by the networking community is enormous, and it is difficult to quantify how much of that research is done using ad-hoc simulation tools.

Besides that, the list of general-purpose DES frameworks is even more vast^[See, e.g., [https://en.wikipedia.org/wiki/List_of_discrete_event_simulation_software](https://en.wikipedia.org/wiki/List_of_discrete_event_simulation_software).], and most of them are unknown within the networking community because they are generally more suited for other fields, such as operations research. Among them, the `SimPy` Python package`r margincite("SimPy")` has received increased attention, and has inspired similar frameworks for other languages, such as `SimJulia` [@GitHub:SimJulia]. Nonetheless, some studies showed that SimPy may not scale for large network simulations [@bahouth2007, @weingartner2009].
